url: https://whispyy.github.io
baseurl: /Tradfacile

# Site settings
title: TradFacile
email: contact@tradfacile.com
description: "Tradfacile, traduction et interprétariat."


# Team names, titles and social links
people:
- name: Nos Engagements
  pic: 1
  position: <ul style="text-align:justify;"><li>Fournir une prestation de haute qualité</li><li>Respecter les délais demandés</li><li>Accompagner nos clients</li></ul>
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Notre différence
  pic: 2
  position: <ul style="text-align:justify;"><li>Des étudiants bilingues et trilingues</li><li>Des solutions et services adaptés</li><li>Collaboration avec des experts</li></ul>
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Nos valeurs
  pic: 3
  position: <ul style="text-align:justify;"><li>Assurer la confidentialité de vos documents</li><li>Apporter notre valeur ajoutée</li><li>Proposer les meilleurs tarifs</li></ul>
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/whispyy
  - title: github
    url: http://github.com/whispyy
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket
  #   url: http://bitbucket.org/jekyll
  # - title: facebook
  #   url:

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
